### ISSUE TITLE
/v1/session directory missing in challenges?

### ISSUE THREAD

**Issue by BitSledge** [thomasameisel/VandyCSCTF#1]
Hello,

I havent compiled a list of each affected challenge, but I have noticed a few with this issue, im currently referencing login_in_source.  
The index page will load presenting a login, you can see the password in the source but the login page doesnt work. The code is making references to /v1/session  which doesnt exist. Am i missing something?

**Comment by thomasameisel** [comment]
To run each challenge, you should first run <code>npm install</code> then <code>node index.js</code> in your command line in the root directory of the challenge. This will run the server, and the server has endpoints that the front-end will call.

**Comment by thomasameisel** [comment]
Actually, you should first call "npm install" to install dependencies then "node index.js" to run the server.

**Comment by BitSledge** [comment]
For that to work, would they all need to be on the same server? it looks like you have this setup for AWS. At the moment I have each challenge on its own Ubuntu VM with a LAMP stack, which might be part of the problem.

**Comment by thomasameisel** [comment]
Each challenge has its own server, so having each challenge on a different VM is fine. I put a couple challenges on different AWS instances. Also, this doesn't necessarily have to be on AWS. It can be on any type of machine.

So you should go into the <code>login_in_source</code> folder then run <code>npm install</code> then <code>node index.js</code>. Then you should be able to go to localhost on whatever port the server uses (8081 for <code>login_in_source</code> -- <code>http://localhost:8081</code>) and see the challenge.

**Comment by thomasameisel** [comment]
So you should go into the "login_in_source" folder then run "npm install" then "node index.js". Then you should be able to go to localhost on whatever port you're using and see the challenge.

**Comment by BitSledge** [comment]
Thanks man! Works great.
